---
# file: roles/idrac-firmware/tasks/main.yml

- name: Make sure iDrac is ready
  local_action: idrac username={{lom_user}} password={{lom_pass}}
                hostname={{lom_hostname}} command="CheckReadyState"
  
- debug: var=lom_hostname

- include: idrac.yml
  when: LifecycleControllerVersion != target_LifecycleControllerVersion 

- include: bios.yml
  when: BIOSVersionString != target_BIOSVersionString


