- hosts: 
   - edge
   - mid
  gather_facts: False
  vars:
    - target_BIOSVersionString: "1.2.10"
    - target_LifecycleControllerVersion: "2.10.10.10"
  roles:
    - idrac-facts
  tasks:
  # - debug: var=lom_hostname
  # - debug: var=BIOSVersionString
  - fail: msg="Mismatch BIOS version {{ BIOSVersionString }} != {{ target_BIOSVersionString }}"
    when:  BIOSVersionString != target_BIOSVersionString

##  - debug: var=LifecycleControllerVersion
  - fail: msg="Mismatch LifeCycle Controller version {{ LifecycleControllerVersion }} != {{ target_LifecycleControllerVersion }}"
    when:  LifecycleControllerVersion != target_LifecycleControllerVersion

#  - name: Is the iDrac hosed?
#    local_action: idrac username={{lom_user}} password={{lom_pass}}
#                  hostname={{lom_hostname}} command="GetRemoteServicesAPIStatus"
#    register: result
#    ignore_errors: True
#    failed_when: ((result.LCStatus != "0") and (result.Status != '0'))

  - name: Get Virtual Disks
    command: wsman enumerate http://schemas.dell.com/wbem/wscim/1/cim-schema/2/root/dcim/DCIM_VirtualDiskView -h {{ lom_hostname }} -u {{ lom_user }} -p {{ lom_pass }} -P 443 -c Dummy -y basic -V –v –M epr
    connection: local
    register: vdisks
    changed_when: False

  - fail: msg="Vdisk Name not set to Boot" 
    when: vdisks.stdout.find("<n1:Name>Boot</n1:Name>") <= 0

  - debug: msg="Vdisk is set to Boot"
    when: vdisks.stdout.find("<n1:Name>Boot</n1:Name>") >= 0



