---
# file: idrac.yml

- hosts: localhost
  tasks:

  - name: Copy XML file to /var/samba
    copy: src=files/idrac_xml/ dest=/var/samba/ directory_mode=yes mode=644
          #owner=ansible group=ansible mode=644

  - name: Download R730xd iDRAC firmware from Dell
    get_url: url=http://downloads.dell.com/FOLDER02881013M/1/iDRAC-with-Lifecycle-Controller_Firmware_FM1PC_WN64_2.10.10.10_A00.EXE
      dest=/var/samba/firmware/730xd/idrac/2.10.10.10.EXE

  - name: Download R730xd BIOS from Dell
    get_url: url=http://downloads.dell.com/FOLDER02868051M/1/BIOS_XR23Y_WN64_1.2.10.EXE
      dest=/var/samba/firmware/730xd/bios/1.2.10.EXE

- hosts:
   - edge
   - mid
  gather_facts: False

  # I left this in for debugging puposes for when we get ready for the 720xd
  #- debug: msg="Looks like this is a 730xd"
  #  when: Model.find('730xd') != -1
  #  #when: Model == 'PowerEdge R730xd'

  roles:
    - idrac-facts
    - idrac-firmware
    - idrac-storage
    - idrac-iso
