// Copyright (c) 2010 Dell Inc.  All rights reserved.
// ==================================================================
// DCIM_LocalUserIdentity
// ==================================================================  
  [ 
      Description (
      "DCIM_LocalUserIdentity is a derivation of DCIM_Identity."
      "An instance of an Identity represents a ManagedElement that "
      "acts as a security principal within the scope in which it is defined and " 
      "authenticated.")
]
class DCIM_LocalUserIdentity : DCIM_Identity
{ 
};
