// Copyright (c) 2010 Dell Inc.  All rights reserved.
// ==================================================================
// DCIM_IPMICLPElementCapabilities
// ==================================================================  
  [ 
      Association, Description (
      "DCIM_IPMICLPElementCapabilities is a derivation of  "
      "CIM_ElementCapabilities."
      "ElementCapabilities represents the association between "
      "ManagedElements and their Capabilities.")
  ]
class DCIM_IPMICLPElementCapabilities : CIM_ElementCapabilities
{                                      
};
