[Description(
       "The DCIM_iDRACCardInteger object may be used to instantiate "
       "integer-based iDRAC Network attributes.")]
class DCIM_iDRACCardInteger : DCIM_iDRACCardAttribute {

      [Description (
          "The property defines a lower bound or limit when "
          "modifying this attribute." ),
       ModelCorrespondence { "CIM_BIOSInteger.UpperBound" }]
   sint64 LowerBound;

      [Description (
          "The property defines an upper bound or limit when "
          "modifying this attribute." ),
       ModelCorrespondence { "CIM_BIOSInteger.LowerBound" }]
   sint64 UpperBound;
};

