// ==================================================================
// DCIM_CSCapacitiesConcreteCollection
// ==================================================================

    [Description(
        "DCIM_CSCapacitiesConcreteCollection is a"
        "trivial derivation of CIM_ConcreteCollection") ]
class DCIM_CSCapacitiesConcreteCollection : CIM_ConcreteCollection 
{

};