// Copyright (c) 2010 Dell Inc.  All rights reserved.
// ==================================================================
// DCIM_CLPServiceAffectsIdentity
// ==================================================================  
  [ 
      Association,
      Description (
      "DCIM_CLPServiceAffectsIdentity is a derivation of  "
      "CIM_ServiceAffectsElement."
      "ServiceAffectsElement represents an association between a "
      "Service and the ManagedElements that might be affected by its execution.")
  ]
class DCIM_CLPServiceAffectsIdentity : CIM_ServiceAffectsElement
{                                      
};
