// ==================================================================
// DCIM_CSSettingsConcreteCollection
// ==================================================================

    [Description(
        "DCIM_CSSettingsConcreteCollection is a"
        "trivial derivation of CIM_ConcreteCollection") ]
class DCIM_CSSettingsConcreteCollection : CIM_ConcreteCollection 
{

};