// Copyright (c) 2010 Dell Inc.  All rights reserved.
// ==================================================================
// DCIM_CLPIdentity
// ==================================================================  
  [ 
      Description (
      "DCIM_CLPIdentity is a derivation of DCIM_Identity."
      "DCIM_Identity is a derivation of CIM_Identity."
      "An instance of an Identity represents a ManagedElement that "
      "acts as a security principal within the scope in which it is defined and " 
      "authenticated.")
]
class DCIM_CLPIdentity : DCIM_Identity
{ 
};
