// ==================================================================
// DCIM_CSCapabilitiesConcreteCollection
// ==================================================================

    [Description(
        "DCIM_CSCapabilitiesConcreteCollection is a"
        "trivial derivation of CIM_ConcreteCollection") ]
class DCIM_CSCapabilitiesConcreteCollection : CIM_ConcreteCollection 
{

};
