// ==================================================================
// DCIM_SPCapabilitiesMemberOfCollection
// ==================================================================

    [Association, Description(
        "DCIM_SPCapabilitiesMemberOfCollection is a"
        "trivial derivation of CIM_MemberOfCollection") ]
class DCIM_SPCapabilitiesMemberOfCollection : CIM_MemberOfCollection 
{};
