[Description(
      "DCIM_CumBaseMetricDefinition is a derivation of "
      "CIM_BaseMetricDefinition and represents the definitional "
      "aspects of a metric.")]
class DCIM_BaseMetricDefinition : CIM_BaseMetricDefinition
{
};