// ==================================================================
// DCIM_SPConsolesConcreteCollection
// ==================================================================

    [Description(
        "DCIM_SPConsolesConcreteCollection is a"
        "trivial derivation of CIM_ConcreteCollection") ]
class DCIM_SPConsolesConcreteCollection : CIM_ConcreteCollection 
{

};