// ==================================================================
// DCIM_SPLogsConcreteCollection
// ==================================================================

    [Description(
        "DCIM_SPLogsConcreteCollection is a"
        "trivial derivation of CIM_ConcreteCollection") ]
class DCIM_SPLogsConcreteCollection : CIM_ConcreteCollection 
{

};