---
# file: roles/idrac-iso/tasks/main.yml

- name: Login to Traffic Ops
  connection: local
  uri: url={{traffic_ops_url}}/login method=POST status_code=302
       body="u={{traffic_ops_user}}&p={{traffic_ops_pass}}"
       HEADER_Content-Type="application/x-www-form-urlencoded"
  register: login

- debug: var=login

- name: Download ISO to /var/samba
  connection: local
  uri: url={{traffic_ops_url}}/iso_download?osversion={{os_version}}&hostname={{inventory_hostname}}&dhcp=no&ipaddr={{ipv4}}&netmask={{ipv4_netmask}}&gateway={{ipv4_gw}}&ip6_address={{ipv6_urlenc}}&ip6_gateway={{ipv6_gw_urlenc}}&dev={{interface}}&mtu={{mtu}}&ondisk={{ondisk}} method=GET HEADER_Cookie="{{ login.set_cookie }}" dest=/var/samba/{{inventory_hostname}}.iso

- name: Detach all SD Card Partitions
  local_action: idrac username={{lom_user}} password={{lom_pass}}
    hostname={{lom_hostname}} command="DetachSDCardPartitions"

- name: Install to server
  local_action: idrac username={{lom_user}} password={{lom_pass}}
    hostname={{lom_hostname}} command="BootToNetworkISO"
    share_pass={{share_pass}} share_user={{share_user}}
    share_ip={{share_ip}} share_name={{share_name}}
    share_type={{share_type}} iso_image={{inventory_hostname}}.iso
  notify:
    - Wait for server to come back
